USE POMS;

SELECT COUNT(1) FROM `order`;	

SELECT LAST_INSERT_ID() FROM `ORDER`;

SELECT * FROM CANCEL_ORDER;

SELECT * FROM `ORDER`;

SELECT * FROM `ORDERED_ITEM`;

/* STORED PROCEDURE FOR UPDATE NAME*/
DELIMITER //
CREATE PROCEDURE update_Customer_Name(IN LOCAL_CUSTOMER_NAME VARCHAR(15), IN LOCAL_ORDER_ID int)
BEGIN
	UPDATE `ORDER` SET CUSTOMER_NAME = LOCAL_CUSTOMER_NAME
    WHERE ORDER_ID = LOCAL_ORDER_ID;
END //
DELIMITER ;

/* STORED PROCEDURE FOR UPDATE CONTACT*/
DELIMITER //
CREATE PROCEDURE update_Customer_Contact(IN LOCAL_CUSTOMER_CONTACT VARCHAR(15), IN LOCAL_ORDER_ID int)
BEGIN
	UPDATE `ORDER` SET CUSTOMER_CONTACT = LOCAL_CUSTOMER_NAME
    WHERE ORDER_ID = LOCAL_ORDER_ID;
END //
DELIMITER ;

/* STORED PROCEDURE FOR UPDATE ADDRESS*/
DELIMITER //
CREATE PROCEDURE update_Customer_Address(IN LOCAL_CUSTOMER_ADDRESS VARCHAR(15), IN LOCAL_ORDER_ID int)
BEGIN
	UPDATE `ORDER` SET DELIVERY_ADDRESS = LOCAL_CUSTOMER_NAME
    WHERE ORDER_ID = LOCAL_ORDER_ID;
END //
DELIMITER ;

/* STORED PROCEDURE TO GET ITEM DETAILS */
DELIMITER //
CREATE PROCEDURE  get_Item_Details(IN LOCAL_ORDER_ID int)
BEGIN
	SELECT * FROM ORDER_ITEM
    WHERE ORDER_ID = LOCAL_ORDER_ID;
END //
DELIMITER ;

/* STORED PROCEDURE TO GET ORDERS PLACED*/
DELIMITER //
CREATE PROCEDURE  get_Order(IN LOCAL_ORDER_ID int)
BEGIN
	SELECT * FROM `ORDER`
    WHERE ORDER_ID = LOCAL_ORDER_ID;
END //
DELIMITER ;

/* STORED PROCEDURE TO GET CANCEL ORDER PLACED*/
DELIMITER //
CREATE PROCEDURE  get_Cancel_Order()
BEGIN
	SELECT * FROM CANCEL_ORDER;
END //
DELIMITER ;

/* STORED PROCEDURE TO DELETE ORDERS PLACED*/
DELIMITER //
CREATE PROCEDURE  delete_Order(IN LOCAL_ORDER_ID int)
BEGIN
	DELETE FROM `ORDER`
    WHERE ORDER_ID = LOCAL_ORDER_ID;
END //
DELIMITER ;

/* STORED PROCEDURE TO DELETE ORDERED ITEM PLACED*/
DELIMITER //
CREATE PROCEDURE  delete_Order_Item(IN LOCAL_ORDER_ID int)
BEGIN
	DELETE FROM ORDERED_ITEM
    WHERE ORDER_ID = LOCAL_ORDER_ID;
END //
DELIMITER ;

/* STORED PROCEDURE TO INSERT ORDERS PLACED*/
DELIMITER //
CREATE PROCEDURE  place_Order(IN  CUSTOMER_NAME VARCHAR(50),IN CONTACT VARCHAR(10),IN ADDRESS VARCHAR(255),IN DELIVERY_STATUS VARCHAR(20))
BEGIN
	INSERT INTO `ORDER`(CUSTOMER_NAME,CUSTOMER_CONTACT,DELIVERY_ADDRESS,DELIVERY_STATUS) VALUES(CUSTOMER_NAME,CONTACT,ADDRESS,DELIVERY_STATUS);
END //
DELIMITER ;
SELECT * FROM `ORDER`;

/* STORED PROCEDURE TO ADD ORDER ITEM*/
DELIMITER //
CREATE PROCEDURE  add_Order_item(IN  ORDER_ID INT,IN ITEM_NAME VARCHAR(255),IN PRICE INT)
BEGIN
	INSERT INTO ORDER_ITEM VALUES(ORDER_ID,ITEM_NAME,PRICE);
END //
DELIMITER ;

/* STORED PROCEDURE TO ADD ORDER ITEM*/
DELIMITER //
CREATE PROCEDURE  add_Order_item(IN  ORDER_ID INT,IN ITEM_NAME VARCHAR(255),IN PRICE INT)
BEGIN
	INSERT INTO ORDER_ITEM VALUES(ORDER_ID,ITEM_NAME,PRICE);
END //
DELIMITER ;


